### PR TITLE
add hover-over descriptions 

### PR DESCRIPTION
**Pull request by glass-w**
## Description
Addresses #105. 

## Todos
This PR adds hover-over "info" icons to columns in the Sprint dashboard using [popovers](https://getbootstrap.com/docs/4.0/components/popovers/).
  - [x] Add hover-overs  to "transformations" page
  - [ ] Test formatting locally (related to #106)

## Questions
  - [ ] Add hover-overs to "summary" page (?)
  - [ ] Add hover-overs to "compounds" page (?)
  - [ ] Add hover-overs to "microstates" page (?)

## Status
- [ ] Ready to go

### CODE REVIEW

**Comment by glass-w** [comment]
Currently, in order to view the changes in [index.html](https://github.com/choderalab/fah-xchem/blob/update-dash-docs/fah_xchem/analysis/website/templates/transformations/index.html) [these lines](https://github.com/choderalab/fah-xchem/blob/update-dash-docs/fah_xchem/analysis/website/templates/base.html#L9-L18) need to be added at the top of the file (I am removing these when adding commits).

I don't think they are needed for the final rendering of the page on the dashbaord since it looks like in the [current dashboard](https://fah-public-data-covid19-moonshot-sprints.s3.us-east-2.amazonaws.com/dashboards/sprint-5/sprint-5-x12073-monomer-neutral/transformations/index.html) the styles are carried forward but I can't guarentee this. 

@mcwitt do you have any ideas here? I'm tempted to just add the above lines to [index.html](https://github.com/choderalab/fah-xchem/blob/update-dash-docs/fah_xchem/analysis/website/templates/transformations/index.html) to ensure the hover-overs work as intended.

**Comment by glass-w** [comment]
Quick preview of how the hover-over feature looks:

Screenshot 2020-11-24 at 12 01 16

**Comment by mcwitt** [comment]
@glass-w updates look awesome!

> It looks like in the current dashboard the styles are carried forward

That's right---what you've done (adding the function to `base.html`) is how I'd do it too. This way it will be included in all templates that extend `base.html` (which should be all of them) without having to repeat yourself.

It works like this: to generate the final html for e.g. [transformations/index.html](https://github.com/choderalab/fah-xchem/blob/update-dash-docs/fah_xchem/analysis/website/templates/transformations/index.html), the content in the template gets inserted into [base.html here](https://github.com/choderalab/fah-xchem/blob/adec7e95cc6014b2dd650bc2fe727aef7199f31a/fah_xchem/analysis/website/templates/base.html#L87-L88). This happens because of the `extends` declaration in [index.html here](https://github.com/choderalab/fah-xchem/blob/084da4edc8641857aecfe56f67c0d73766005c79/fah_xchem/analysis/website/templates/transformations/index.html#L1).

**Comment by mcwitt** [comment]
@glass-w in case it's useful, I used the following to debug the site generation on my laptop. This requires that you have the analysis results in `results/analysis.json`.

```python
fah-xchem generate-artifacts results/analysis.json --fah-projects-dir "" --fah-data-dir "" --base-url "/" --noplots --nosnapshots --output-dir results --num-procs 8 --log INFO && python -m http.server --directory results
```

Then you can point your browser to http://0.0.0.0:8000/ to see the result.

**Comment by glass-w** [comment]
@mcwitt Great! Thanks so much for all of that, I'll check my changes locally using your example.

**Comment by glass-w** [comment]
This has been superseded by #115

**Pull request closed without merging**
